config/routes.rb
Rails.application.routes.draw do
  root :to => 'stations#index'
  resources :stations
  resources :lines
  resources :stops
end

app/models/line.rb
class Line < ActiveRecord::Base
  validates :name, presence: true
  has_many :stops
  has_many :stations, through: :stops
end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :name, presence: true
  has_many :stops
  has_many :lines, through: :stops
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :line
  belongs_to :station
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def show
    @line = Line.find(params[:id])
  end

  def create
    @line = Line.new(line_params)

    if @line.save
      flash[:notice] = "Line was added"
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(line_params)
      flash[:notice] = "Line updated."
      redirect_to lines_path(@line)
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    if @line.destroy
      flash[:notice] = "The line was deleted."
      redirect_to lines_path
    end
  end

private
  def line_params
    params.require(:line).permit(:name, station_ids: [])
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def show
    @station = Station.find(params[:id])
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = "Station was added"
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(station_params)
      flash[:notice] = "Station updated."
      redirect_to station_path(@station)
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    if @station.destroy
      flash[:notice] = "The station was deleted."
      redirect_to stations_path
    end
  end

  private
    def station_params
      params.require(:station).permit(:name, :line_ids)
    end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
    @stops = Stop.all
  end

  def new
    @stop = Stop.new
  end

  def show
    @stop = Stop.find(params[:id])
  end

  def create
    @stop = Stop.new(stop_params)
    if @stop.save
      flash[:notice] = "Stop was added"
      redirect_to stops_path
    else
      render 'new'
    end
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])
    if @stop.update(stop_params)
      flash[:notice] = "Stop updated."
      redirect_to stops_path(@stop)
    else
      render 'edit'
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    if @stop.destroy
      flash[:notice] = "The stop was deleted."
      redirect_to stops_path
    end
  end

  private
    def stop_params
      params.require(:stop).permit(:station_id, :line_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "bus timetable", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home", '/' %></li>
            <li><%= link_to "Lines", lines_path %></li>
            <li><%= link_to "Stations", stations_path %></li>
            <li><%= link_to "Stops", stops_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-success<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/lines/_form.html.erb
<%= form_for @line do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: "Name" %>
    <%= f.collection_check_boxes :station_ids, Station.all, :id, :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/lines/edit.html.erb
<%= content_for(:title, "Update Line | Bus Timetables") %>

<%= render("layouts/errors", :object => @line) %>

<%= render("form") %>

app/views/lines/index.html.erb
<h1>All Lines</h1>
<ul>
  <% @lines.order('name').each do |line| %>
  <li><a href="<%= line_path(line)%>"><%= line.name %></a></li>
  <% end %>
</ul>

<%= link_to "New line", new_line_path, :class=> "btn btn-default" %>

app/views/lines/new.html.erb
<%= content_for(:title, "New Line | Bus Timetables") %>

<%= render("layouts/errors", :object => @line) %>

<%= render("form") %>

app/views/lines/show.html.erb
<% content_for(:title, "New line | Lines") %>
<h1><%= @line.name %></h1>

<h3>All Stations for this line</h3>
<ul>
  <% @line.stations.each do |station| %>
    <li><%= station.name %></li>
  <% end %>
</ul>

<p><%= link_to "Edit", edit_line_path(@line), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", line_path(@line),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"},
                         :class => "btn btn-danger" %></p>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stations/edit.html.erb
<%= content_for(:title, "Update Station | Bus Timetables") %>

<%= render("layouts/errors", :object => @station) %>

<%= render("form") %>

app/views/stations/index.html.erb
<h1>All Stations</h1>
<ul>
  <% @stations.each do |station| %>
  <li><a href="<%= station_path(station)%>"><%= station.name %></a></li>
  <% end %>
</ul>

<%= link_to "New station", new_station_path, :class=> "btn btn-default" %>

app/views/stations/new.html.erb
<%= content_for(:title, "New Station | Bus Timetables") %>

<%= render("layouts/errors", :object => @station) %>

<%= render("form") %>

app/views/stations/show.html.erb
<% content_for(:title, "New station | Stations") %>
<h1><%= @station.name %></h1>

<h3>All Lines for this station</h3>
<ul>
  <% @station.lines.each do |line| %>
    <li><%=line.name %></li>
  <% end %>
</ul>
<p><%= link_to "Edit", edit_station_path(@station), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", station_path(@station),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"},
                         :class => "btn btn-danger" %></p>

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <div class="form-group"></div>
    <%= f.collection_select :station_id, Station.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stops/edit.html.erb
<%= content_for(:title, "Update Stop | Bus Timetables") %>

<%= render("layouts/errors", :object => @stop) %>

<%= form_for(@stop) do |f| %>
  <%= f.collection_select :station_id, Station.all, :id, :name %>
  <%= f.collection_select :line_id, Line.all, :id, :name %>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stops/index.html.erb
<h1>All Stops</h1>


<%= link_to "New stop", new_stop_path, :class=> "btn btn-default" %>

app/views/stops/new.html.erb
<%= content_for(:title, "New Stop | Bus Timetables") %>

<%= render("layouts/errors", :object => @stop) %>

<%= render("form") %>

app/views/stops/show.html.erb
<% content_for(:title, "New stop | Stops") %>
<h1><%= @stop.id %></h1>
<p><%= link_to "Edit", edit_stop_path(@stop), :class => "btn btn-default" %></p>
<p><%= link_to "Delete", stop_path(@stop),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"},
                         :class => "btn btn-danger" %></p>